steps:

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

#name: 'gcr.io/cloud-builders/npm'
#args: ['run', 'test']

- name: 'eu.gcr.io/kujakuja-dev/cloud-build-api'
  args: ['mv', 'src/AppConfig.js.template', 'src/AppConfig.js']

- name: 'eu.gcr.io/kujakuja-dev/envsubst'
  args: ['src/AppConfig.js']
  env:
  - 'ROOT_API_URL=https://api.datos.kujakuja.com'
  - 'FRONT_END_URL=https://datos.kujakuja.com/es/'
  secretEnv:
  - 'MAPBOX_GL_ACCESS_TOKEN'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--no-promote', '--version=$TAG_NAME', '--project=kujakuja-datos-live']

secrets:
  - kmsKeyName: projects/kujakuja-dev/locations/europe/keyRings/cloud-build/cryptoKeys/config-secrets
    secretEnv:
      MAPBOX_GL_ACCESS_TOKEN: CiQAnpDxcUldqeVAEUG1HAc+YEHq0bB35dtMgzaCmu6/f3czILQSjQEA/Du3ijWYdBvmFDUPcTVb5yG1MURAmf9V+dDp+aXODTqZSJEbRgk51FXEkyyYfiu6FbA9uIVv0jUEGq4t0zydet62sQoZezEjaNeH90yfuyON4lpfDp5VoVvlOeNeB5IiugcdNCG9YVHrLSsZuLESGerdWME5CxDcbneyJitG5szfcW/C5XXFoTW4S6o=

timeout: '900s'
